name = "TrajectoryGamesExamples"
uuid = "ff3fa34c-8d8f-519c-b5bc-31760c52507a"
authors = ["David Fridovich-Keil<dfk@utexas.edu>", "Forrest Laine<forrest.laine@vanderbilt.edu>", "Lasse Peters<lasse.peters@mailbox.org>"]
version = "0.1.10"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
TrajectoryGamesBase = "ac1ac542-73eb-4349-ae1b-660ab3609574"

[compat]
BlockArrays = "0.16"
Colors = "0.12"
InfiniteArrays = "0.12, 0.13, 0.14"
Makie = "0.17, 0.18, 0.19, 0.20"
TrajectoryGamesBase = "0.2, 0.3"
julia = "1.7"
