name: CI
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        julia_version: ["1"]
    name: julia ${{ matrix.julia_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia_version }}
      - uses: julia-actions/cache@v1
      #- uses: julia-actions/julia-runtest@latest
      #  with:
      #    prefix: xvfb-run
      - name: Test
        shell: xvfb-run julia --project=. {0}
        run: |
          using Pkg
          pkg"add TrajectoryGamesBase#release-0.4"
          Pkg.test(; coverage=true)
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
